[package]
name = "pithos"
description = "Client for the Pithos object storage file format"
version = "0.6.1"
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
anyhow = "1.0.93"
async-channel = "2.3.1"
async-trait = "0.1.83"
base64 = "0.22.1"
borsh = {version = "1.5.3", features = ["std", "derive"]}
bytes = "1.8.0"
chacha20poly1305 = "0.10.1"
clap = { version = "4.5.21", features = ["derive"] }
crypto_kx = { version = "0.2.1", features = ["serde"] }
dotenvy = "0.15.7"
futures = "0.3.31"
futures-util = "0.3.31"
openssl = "0.10.68"
pithos_lib = { path = "../pithos_lib", version="0.6.1"}
rand = "0.8.5"
serde_json = "1.0.133"
tokio = { version = "1.41.1", features = ["full"] }
tokio-stream = "0.1.16"
tokio-util = "0.7.12"
tracing = "0.1.40"
tracing-subscriber = {version = "0.3.18", features = ["env-filter", "time"]}
x25519-dalek = "2.0.1"
indicatif = "0.17.9"