[package]
name = "pithos_lib"
description = "Library and components for encrypting / compressing pithos (.pto) files, including specification"
version = "0.6.2"
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.98"
async-compression = { version = "0.4.23", features = ["tokio", "zstd", "gzip"] }
hex = "0.4.3"
chacha20poly1305 = "0.10.1"
byteorder = "1.5.0"
bytes = "1.10.1"
tokio = { version = "1.45.0", features = ["full"] }
tokio-util = "0.7.15"
async-trait = "0.1.88"
hyper = { version = "1.6.0", features = ["full"] }
futures = "0.3.31"
async-channel = "2.3.1"
async-stream = "0.3.6"
tar = "0.4.44"
digest = "0.10.7"
async_zip = { version = "0.0.17", features = ["chrono", "tokio", "deflate"] }
pin-project = "1.1.10"
tracing = "0.1.41"
md-5 = "0.10.6"
sha1 = "0.10.6"
sha2 = "0.10.9"
blake2 = "0.10.6"
rand_core = "0.9.3"
thiserror = "2.0.12"
crypto_kx = "0.2.1"
base64 = "0.22.1"
scrypt = { version = "0.11.0" }
borsh = { version = "1.5.7", features = ["std", "derive"] }
itertools = "0.14.0"
serde = { version = "1.0.219", features = ["derive"] }

[dev-dependencies]
criterion = { version = "0.6.0", features = ["html_reports", "async_tokio"] }
pithos = { path = "../pithos" }

[[bench]]
name = "performance"
harness = false
