[package]
name = "pithos_lib"
description = "Library and components for encrypting / compressing pithos (.pto) files, including specification"
version = "0.6.1"
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.98"
chacha20poly1305 = "0.10.1"
byteorder = "1.5.0"
digest = "0.10.7"
sha3 = "0.10.8"
rand_core = "0.6.4"
thiserror = "2.0.3"
scrypt = { version = "0.11.0" }
integer-encoding = "4.0.2"
pkcs8 = { version = "0.10.2", features = ["pem", "alloc"] }
x25519-dalek = { workspace = true }
rand = "0.8"
fastcdc = "3.2.1"
zstd = "0.13.3"
crc32fast = "1.5.0"
blake3 = "1.8.2"
